# Generated by Django 2.2.3 on 2019-07-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_prazo', models.DateTimeField()),
                ('hora_prazo', models.TimeField()),
                ('status_projeto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('data_prazo', models.DateTimeField()),
                ('hora_prazo', models.TimeField()),
                ('status_tarefa', models.CharField(max_length=255)),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.Projeto')),
            ],
        ),
    ]
