# Generated by Django 2.2.3 on 2019-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_prazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_prazo',
            field=models.DateField(),
        ),
    ]
