# Generated by Django 2.2.3 on 2019-07-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20190712_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='projeto',
        ),
    ]
